version: "3"

services:
  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=testing
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data: {}